#!/usr/bin/env python
"""
train_lora.py - Step 3b: Train a Stable Diffusion 1.5 LoRA on Manga109 cropped panels and captions.

This script parses text/image datasets generated by data_prep.py and performs a custom
HuggingFace diffusers training loop using PEFT to target UNet attention layers.

Usage:
    python train_lora.py --data_dir ./step-3/output_real --output_dir ./Step-4-lora-training/output/final_lora --epochs 5
"""

import os
import argparse
import logging
from pathlib import Path
import torch
from torch.utils.data import Dataset, DataLoader
from PIL import Image
from tqdm import tqdm
from transformers import CLIPTokenizer, CLIPTextModel
from diffusers import UNet2DConditionModel, DDPMScheduler, AutoencoderKL
from diffusers.optimization import get_scheduler
from peft import LoraConfig, get_peft_model

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("lora_training")


class MangaLoRADataset(Dataset):
    def __init__(self, data_dir: Path, tokenizer, size: int = 512):
        self.data_dir = Path(data_dir)
        self.images_dir = self.data_dir / "images"
        self.captions_dir = self.data_dir / "captions"
        self.tokenizer = tokenizer
        self.size = size

        if not self.images_dir.exists() or not self.captions_dir.exists():
            raise FileNotFoundError(
                f"Data directory {data_dir} must contain 'images/' and 'captions/' subfolders. "
                "Ensure data_prep.py has run successfully."
            )

        # Get list of files
        self.image_paths = sorted(list(self.images_dir.glob("*.png")) + list(self.images_dir.glob("*.jpg")))
        logger.info(f"Loaded {len(self.image_paths)} images from {self.images_dir}")

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        stem = img_path.stem
        txt_path = self.captions_dir / f"{stem}.txt"

        # Load caption
        caption = ""
        if txt_path.exists():
            with open(txt_path, "r", encoding="utf-8") as f:
                caption = f.read().strip()
        else:
            logger.warning(f"No caption found for image {img_path.name}, using empty prompt.")

        # Load image & convert to float tensor normalized to [-1, 1]
        try:
            image = Image.open(img_path).convert("RGB").resize((self.size, self.size), Image.Resampling.LANCZOS)
        except Exception as e:
            logger.error(f"Error loading image {img_path}: {e}")
            # return blank dummy image on failure
            image = Image.new("RGB", (self.size, self.size), (255, 255, 255))

        # PyTorch preprocessing for SD inputs
        pixel_values = torch.from_numpy(torch.tensor(image).permute(2, 0, 1).numpy()).float()
        pixel_values = (pixel_values / 127.5) - 1.0

        # Tokenize prompt text
        input_ids = self.tokenizer(
            caption,
            max_length=self.tokenizer.model_max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        ).input_ids[0]

        return {"pixel_values": pixel_values, "input_ids": input_ids}


def main():
    parser = argparse.ArgumentParser(description="Train a LoRA on Stable Diffusion 1.5 using Manga109 dataset crops")
    parser.add_argument("--pretrained_model_name_or_path", type=str, default="stable-diffusion-v1-5/stable-diffusion-v1-5", help="Path or HuggingFace repo ID of the base Stable Diffusion model")
    parser.add_argument("--data_dir", type=str, default="./step-3/output_real", help="Directory where dataset images/ and captions/ are stored")
    parser.add_argument("--output_dir", type=str, default="./Step-4-lora-training/output/final_lora", help="Directory to save the trained LoRA weights")
    parser.add_argument("--epochs", type=int, default=10, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=2, help="Training batch size")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate for optimization")
    parser.add_argument("--rank", type=int, default=16, help="LoRA rank (r) value (FIX 2b: bumped from 4 to 16 for capacity)")
    parser.add_argument("--lora_alpha", type=int, default=32, help="LoRA alpha scaling factor")
    parser.add_argument("--mixed_precision", type=str, default="fp16", choices=["no", "fp16", "bf16"], help="Mixed precision mode to reduce VRAM requirements")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for reproducibility")
    args = parser.parse_args()

    # Seed setup
    torch.manual_seed(args.seed)

    # Initialize models
    logger.info("Initializing Stable Diffusion components...")
    try:
        tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
        text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="text_encoder")
        vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder="vae")
        unet = UNet2DConditionModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="unet")
    except Exception as e:
        logger.error(f"Failed to load pretrained Stable Diffusion weights: {e}")
        return

    # Freeze VAE & Text Encoder to only update UNet LoRA layers
    vae.requires_grad_(False)
    text_encoder.requires_grad_(False)
    unet.requires_grad_(False)

    # Device & precision settings
    device = "cuda" if torch.cuda.is_available() else "cpu"
    weight_dtype = torch.float32
    if args.mixed_precision == "fp16":
        weight_dtype = torch.float16
    elif args.mixed_precision == "bf16":
        weight_dtype = torch.bfloat16

    vae.to(device, dtype=weight_dtype)
    text_encoder.to(device, dtype=weight_dtype)

    # FIX 2 + 2b: Target UNet attention layers using PEFT LoRA Config with Rank=16
    lora_config = LoraConfig(
        r=args.rank,
        lora_alpha=args.lora_alpha,
        target_modules=["to_q", "to_k", "to_v", "to_out.0"],
        lora_dropout=0.0,
        bias="none",
    )
    unet = get_peft_model(unet, lora_config)
    unet.to(device)

    # Set up noise scheduler & optimizer
    noise_scheduler = DDPMScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
    optimizer = torch.optim.AdamW(unet.parameters(), lr=args.lr)

    # Dataset & Dataloader setup
    try:
        dataset = MangaLoRADataset(Path(args.data_dir), tokenizer)
        dataloader = DataLoader(dataset, batch_size=args.batch_size, shuffle=True, drop_last=True)
    except Exception as e:
        logger.error(f"Failed to initialize dataset or dataloader: {e}")
        return

    # LR Scheduler
    num_update_steps_per_epoch = len(dataloader)
    max_train_steps = args.epochs * num_update_steps_per_epoch
    lr_scheduler = get_scheduler("constant", optimizer=optimizer, num_warmup_steps=0, num_training_steps=max_train_steps)

    logger.info("***** Starting LoRA Training Loop *****")
    logger.info(f"  Target rank = {args.rank}, Alpha = {args.lora_alpha}")
    logger.info(f"  Total epochs = {args.epochs}")
    logger.info(f"  Batch size = {args.batch_size}")
    logger.info(f"  Total train steps = {max_train_steps}")

    unet.train()
    for epoch in range(args.epochs):
        epoch_loss = 0.0
        progress_bar = tqdm(total=len(dataloader), desc=f"Epoch {epoch + 1}/{args.epochs}")
        for step, batch in enumerate(dataloader):
            optimizer.zero_grad()

            pixel_values = batch["pixel_values"].to(device, dtype=weight_dtype)
            input_ids = batch["input_ids"].to(device)

            # Get latent vectors from VAE
            latents = vae.encode(pixel_values).latent_dist.sample()
            latents = latents * 0.18215

            # Sample noise to add to the latents
            noise = torch.randn_like(latents)
            bsz = latents.shape[0]
            # Sample a random timestep for each image
            timesteps = torch.randint(0, noise_scheduler.config.num_train_timesteps, (bsz,), device=latents.device)
            timesteps = timesteps.long()

            # Add noise to the latents according to the noise magnitude at each timestep
            noisy_latents = noise_scheduler.add_noise(latents, noise, timesteps)

            # Get the text embedding for conditioning
            encoder_hidden_states = text_encoder(input_ids)[0]

            # Predict the noise residual
            model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample

            # Get target loss type
            if noise_scheduler.config.prediction_type == "epsilon":
                target = noise
            elif noise_scheduler.config.prediction_type == "v_prediction":
                target = noise_scheduler.get_velocity(latents, noise, timesteps)
            else:
                raise ValueError(f"Unknown prediction type {noise_scheduler.config.prediction_type}")

            # Compute MSE loss
            loss = torch.nn.functional.mse_loss(model_pred.float(), target.float(), reduction="mean")
            loss.backward()

            optimizer.step()
            lr_scheduler.step()

            epoch_loss += loss.item()
            progress_bar.update(1)
            progress_bar.set_postfix({"loss": loss.item()})

        avg_loss = epoch_loss / len(dataloader)
        logger.info(f"Epoch {epoch + 1} finished with average loss: {avg_loss:.6f}")

    # Save final LoRA weights in Diffusers-compatible load_lora_weights structure
    output_path = Path(args.output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    # PEFT allows saving weights via save_pretrained
    logger.info(f"Saving final trained LoRA adapters to: {output_path}")
    unet.save_pretrained(str(output_path))
    
    # Create companion README or tag file
    (output_path / "metadata.txt").write_text(
        f"Base Model: {args.pretrained_model_name_or_path}\nRank: {args.rank}\nAlpha: {args.lora_alpha}\n"
    )
    logger.info("Training complete and LoRA weights saved successfully.")


if __name__ == "__main__":
    main()
